package Coocook::Schema::ResultSet::Recipe;

use Moose;
use MooseX::MarkAsMethods autoclean => 1;

extends 'Coocook::Schema::ResultSet';

__PACKAGE__->load_components('+Coocook::Schema::Component::ResultSet::SortByName');

__PACKAGE__->meta->make_immutable;

# TODO replace by autogenerated code from Component::Result::ResultsetRelationships
sub recipe_tags {
    my $self = shift;

    return $self->result_source->schema->resultset('RecipeTag')
      ->search( { 'recipe' => { -in => $self->get_column('id')->as_query } } );
}

sub tags {    # TODO replace by autogenerated code from Component::Result::ResultsetRelationships
    my $self = shift;

    return $self->result_source->schema->resultset('Tag')
      ->search( { 'recipes_tags.recipe' => { -in => $self->get_column('id')->as_query } },
        { join => 'recipes_tags' } );
}

1;
